version: '3'

services:
  flask-api:
    build: applications/flask-api
    volumes:  # build images have the code copied inside. Mapping the directory is easier for development
      - ./applications/flask-api:/usr/src/app
    ports:
      - 5678:80
    networks:
      - web-network

  docker-php-fpm:
    build: applications/website
    depends_on:
      - flask-api
    networks:
      - web-network

  docker-nginx:
    build:
      context: ./applications/nginx
    depends_on:
      - docker-php-fpm
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./applications/website:/var/www/html
      - ./applications/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web-network

  mysql-database:
    container_name: mysql-database
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - '3306:3306'
    networks:
      - web-network

networks:
  web-network:
